### ISSUE TITLE
请问FLtrust官方有开源吗？

### ISSUE THREAD

**Issue by Rookie143** [zhmzm/FLTrust_pytorch#1]
我没有在网上找到😭

**Comment by zhmzm** [comment]
在arxiv上搜索fltrust，里面找code。是基于mxnet写的



---原始邮件---
发件人: "hangtao ***@***.***&gt;
发送时间: 2022年4月6日(周三) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhmzm/FLTrust_pytorch] 请问FLtrust有开源吗？ (Issue #1)




 
我没有在网上找到😭

**Comment by zhmzm** [comment]
https://arxiv.org/abs/2012.13995

click demo code:https://people.duke.edu/~zg70/code/fltrust.zip

**Comment by Rookie143** [comment]
好的，谢谢大佬

**Comment by Ronaldo-Stan** [comment]
大佬，你复现出来结果怎么样啊
