### ISSUE TITLE
question about FLTrust

### ISSUE THREAD

**Issue by rideapig** [zhmzm/FLTrust_pytorch#2]
hi, I learned your code and you wrote it very well! After learning, I have some questions about you saying that your code cannot be suitable for RESNET because of the BN layer, may i ask you why you say that? I see that the paper gives an example of FLTrust application on RESNET.
Thanks!

**Comment by zhmzm** [comment]
From my observation, the parameters in bn layers are so significant that affect cosine similarity calculation.  One possible solution is that omit BN layers in cosine similarity calculation, although the writer did not mention it in the paper.

**Comment by rideapig** [comment]
你好，我是施逸铭，我已经收到您的邮件，会尽快给你回复。

**Comment by rideapig** [comment]
> 

Thanks

**Comment by zhmzm** [comment]
> > 
> 
> Thanks

I have updated [a new repository](https://github.com/zhmzm/FLAME) including fltrust code that can support models with BN layers.

**Comment by rideapig** [comment]
你好，我是施逸铭，我已经收到您的邮件，会尽快给你回复。

**Comment by rideapig** [comment]
ok，thanks！




发自我的iPhone


------------------ Original ------------------
From: zhmzm ***@***.***&gt;
Date: Fri,Sep 2,2022 10:00 PM
To: zhmzm/FLTrust_pytorch ***@***.***&gt;
Cc: rideapig ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [zhmzm/FLTrust_pytorch] question about FLTrust (Issue #2)





    
Thanks
  
I have updated a new repository including fltrust code that can support models with BN layers.
